### ISSUE TITLE
.moveAsync options ignored

### ISSUE THREAD

**Issue by simone-sanfratello** [overlookmotel/fs-extra-promise#25] opened 2017-04-07 12:00 UTC
Hi,

using ``fs.moveAsync``, options ``{ overwrite: true }`` are ignored, so if the destination exists, it reject with error EEXIST

please fix like follow

````js
fs.moveAsync = function(src, dst, options) => {
  return new Promise((resolve, reject) {
    fs.move(src, dst, options, (err) => {
      if (err) {
        reject(err)
        return 
      }
      resolve()
    })
  })
}
````

**Comment by overlookmotel** [comment] 2017-04-07 12:06
Have you checked if `fs.move` (i.e. callback version of the function) behaves the same? If so, the problem is with `fs-extra` module, not `fs-extra-promise`. I think that's very much likely to be the cause.

NB The version of `fs-extra` used by this module is v0.30.0, which is now well out of date. So the bug may have been fixed in a more recent version of `fs-extra`. See the README for the `.useFs()` method which allows you to use the most recent `fs-extra` version.

I think it's highly likely this problem is in `fs-extra` not in this module. So I'm going to close this issue. But if I'm wrong, please do re-open the issue and let me know.

**Closed as completed by overlookmotel** 2017-04-07 12:06 UTC

**Comment by simone-sanfratello** [comment] 2017-04-14 11:09
it works in the way you said, using fs-extra@2.x

````js
const fs = require('fs-extra-promise').useFs(require('fs-extra'));
````

thanks

**Comment by overlookmotel** [comment] 2017-04-14 15:13
Great. Thanks for letting me know.

By the way, latest version of `fs-extra-promise` v1.0.1 uses latest version of `fs-extra` (released just last week) so if you update, you shouldn't need to use `.useFs()` any more.

**Comment by simone-sanfratello** [comment] 2017-04-14 15:27
I will, thank you
