### ISSUE TITLE
With co, fs.copyAsync cause CPU 100%

### ISSUE THREAD

**Issue by denghongcai** [overlookmotel/fs-extra-promise#4] opened 2015-08-01 10:43 UTC
I use co to make use of `yield`

```
co(function*(){
  yield fs.copyAsync(target, destination);
})()
```

but fs.copySync works fine
fs-extra-promise version: 0.1.0

**Comment by overlookmotel** [comment] 2015-09-09 09:37
Hi @denghongcai.

Sorry for slow reply. My job has been crazy past few months and I haven't had much time.

I've just published v0.2.1 which updates `bluebird` and `fs-extra` to latest versions. Can you please check if this issue still exists with the new version.

**Comment by overlookmotel** [comment] 2015-09-09 09:37
And did you check if you also got 100% CPU when not using `co`/`yield`?

**Comment by overlookmotel** [comment] 2015-09-21 21:47
Ping @denghongcai

**Comment by denghongcai** [comment] 2015-09-22 02:06
seems not ……

**Comment by denghongcai** [comment] 2015-09-22 02:16
still exists

you can use `fs.copyAsync` to copy linux kernel source code folder

**Comment by overlookmotel** [comment] 2016-07-06 11:56
@denghongcai I'd really like to resolve this issue but need more information.

I'm on OS X so can't test out your "copy linux kernel source code folder" suggestion.

Can you please try out a couple of things?

##### 1. Do you have the same issue without using `co`/`yield`?

``` js
var fs = require('fs-extra-promise');
fs.copyAsync(target, destination).then( function() {
    console.log('done!');
} );
```

##### 2. Do you have the same issue when using `fs-extra` directly rather than the promisified version?

``` js
var fs = require('fs-extra');
fs.copyAsync(target, destination, function() {
    console.log('done!');
} );
```

Please let me know - it's really hard to pinpoint problems and solve them without a bit more information and help in narrowing down where the issue is coming from.

**Comment by overlookmotel** [comment] 2017-04-08 16:45
Since no further response, and I think the issue most likely related to `fs-extra` and not this module, I'm closing this issue.

**Closed as completed by overlookmotel** 2017-04-08 16:45 UTC
